baseURL = "https://desie.netlify.com/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Muhire : Website"
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = "Grenoble, France"
author = "Muhire Desire"
copyright = "Copyright &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"
description = "This is meta description"
email = "stic2013@gmail.com"
google_analytics_id = ""
home = "Home"
logo = "images/logo.png"
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "mailto:stic2013@gmail.com"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.linkedin.com/in/desire-muhire-5789224a/"
icon = "ti-linkedin"
[[params.social]]
URL = "https://twitter.com/muhidesire"
icon = "ti-twitter-alt"
